---

- name: Setar a variavel net.ipv6.conf.all.disable_ipv6
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv6.conf.all.disable_ipv6 = 1

- name: Setar a variavel net.ipv6.conf.default.disable_ipv6
  lineinfile:
    dest: /etc/sysctl.conf	
    line: net.ipv6.conf.default.disable_ipv6 = 1

- name: Setar a variavel net.ipv6.conf.lo.disable_ipv6
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv6.conf.lo.disable_ipv6 = 1

- name: Reload Sysctl
  command: /bin/true
  notify:
    - reload sysctl.conf
    - flush routes

#- name: "sysctl : net.ipv6.conf.all.disable_ipv6"
#  sysctl:
#    name: net.ipv6.conf.all.disable_ipv6
#    value: 1
#    sysctl_set: yes
#    sysctl_file: /etc/sysctl.conf
#    state: present
#    reload: yes

#- name: "sysctl : net.ipv6.conf.default.disable_ipv6"
#  sysctl:
#    name: net.ipv6.conf.default.disable_ipv6
#    value: 1
#    sysctl_set: yes
#    sysctl_file: /etc/sysctl.conf
#    state: present
#    reload: yes


#- name: "sysctl : net.ipv6.conf.lo.disable_ipv6"
#  sysctl:
#    name: net.ipv6.conf.lo.disable_ipv6
#    value: 1
#    sysctl_set: yes
#    sysctl_file: /etc/sysctl.conf
#    state: present
#    reload: yes

# Desabilitar IPV6 no ModProbe
#- name: RedHat | placeholder true for ipv6 in modprobe
#  lineinfile: "dest=/etc/modprobe.conf line='install ipv6 /bin/true' create=yes"
#  notify:
#    - rmmodipv6
#  when: ansible_distribution_file_variety == 'RedHat' and ansible_distribution_major_version >= '7'

#Desabilitar no arquivo sysconfig/network
- name: RedHat | disable ipv6 in sysconfig/network
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    create: yes
  with_items:
    - { regexp: 'NETWORKING_IPV6=.*', line: 'NETWORKING_IPV6=NO' }
    - { regexp: 'IPV6INIT=.*', line: 'IPV6INIT=no' }
  notify:
    - restart network
    - restart NetworkManager
  when: ansible_distribution_file_variety == 'RedHat' and ansible_distribution_major_version >= '7'

#Desabilitar o servico de firewalld
- name: Desabilitar o servico de firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
  register: firewalld_result
  failed_when: "firewalld_result is failed and 'Could not find the requested service' not in firewalld_result.msg"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'

#Desabilitar o NetworkManager
- name: Disable NetworkManager
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    line: NM_CONTROLLED=no
    backup: yes
    create: yes
  notify:
    - remove NetworkManager


...
